document.addEventListener('DOMContentLoaded',()=>{
let cursorTime=0,draggingCursor=false,playToken=0,activeBoundary=0;
const clockShort=s=>{s=Math.max(0,Number(s)||0);let m=Math.floor(s/60),sec=Math.floor(s%60);return String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0')},clockFine=s=>{let base=clockShort(s);return total()<5?base+'.'+Math.floor((s%1)*10):base},clipPx=c=>Math.max(70,dur(c)*pps);
function setPlayIcon(on){playing=on;$('#play').innerHTML=on?svg('<path d="M9 7h3v10H9zM14 7h3v10h-3z"/>'):svg('<path d="m9 7 9 5-9 5z"/>');$('#play').setAttribute('aria-label',on?'Pause':'Lire')}
function positionForTime(t){let x=0,elapsed=0;for(let i=0;i<clips.length;i++){let d=dur(clips[i]),w=clipPx(clips[i]);if(t<=elapsed+d||i===clips.length-1)return x+(d?Math.max(0,Math.min(1,(t-elapsed)/d))*w:0);elapsed+=d;x+=w+3}return x}
function timeForClientX(clientX){let track=$('#videoTrack'),r=track.getBoundingClientRect(),x=Math.max(0,clientX-r.left),elapsed=0,pos=0;for(let i=0;i<clips.length;i++){let d=dur(clips[i]),w=clipPx(clips[i]);if(x<=pos+w)return elapsed+Math.max(0,Math.min(1,(x-pos)/w))*d;elapsed+=d;pos+=w+3}return total()}
function locate(t){let elapsed=0;for(let i=0;i<clips.length;i++){let d=dur(clips[i]);if(t<=elapsed+d||i===clips.length-1)return{i,local:Math.max(0,Math.min(d,t-elapsed)),elapsed};elapsed+=d}return{i:0,local:0,elapsed:0}}
function locateStart(index){let n=0;for(let i=0;i<index;i++)n+=dur(clips[i]);return n}
function updateRuler(){let ruler=$('.ruler'),range=Math.max(total(),1),steps=range<=3?[0,range/3,range*2/3,range]:range<=8?[0,2,4,6]:range<=20?[0,5,10,15]:range<=45?[0,10,20,30]:[0,Math.round(range/3),Math.round(range*2/3),Math.round(range)];ruler.innerHTML=steps.map(v=>'<span>'+clockFine(v)+'</span>').join('')}
function updateCursor(){let ph=$('#playhead'),track=$('#videoTrack');if(!ph||!track)return;ph.style.left=(track.offsetLeft+positionForTime(cursorTime))+'px';$('#time').textContent=clockFine(cursorTime)+' / '+clockFine(total())}
function seekTo(t,loadVideo=true){cursorTime=Math.max(0,Math.min(total(),t));if(clips.length){let p=locate(cursorTime);sel=p.i;if(loadVideo){let c=clips[p.i],v=$('#viewer');if(v.src!==c.url)v.src=c.url;try{v.currentTime=Math.min(c.end,Math.max(c.start,c.start+p.local*c.speed))}catch{}}}updateCursor()}
function addTransitionButtons(){let track=$('#videoTrack');if(!track)return;track.querySelectorAll('.transitionChip').forEach(x=>x.remove());let x=0;clips.forEach((c,i)=>{x+=clipPx(c);if(i<clips.length-1){let b=document.createElement('button');b.className='transitionChip '+(c.transition&&c.transition!=='cut'?'active':'');b.style.left=x+'px';b.title='Transition entre les plans';b.innerHTML=svg('<path d="m7 8 4 4-4 4M17 8l-4 4 4 4"/>');b.onclick=e=>{e.stopPropagation();transitionSheet(i)};track.appendChild(b)}x+=3})}
const renderV34=render;render=function(){renderV34();addTransitionButtons();updateRuler();requestAnimationFrame(updateCursor)};
importFiles=function(fs){[...fs].filter(f=>f.type.startsWith('video/')).forEach(f=>{let url=URL.createObjectURL(f),c={url,name:f.name,start:0,end:0,duration:0,speed:1,transition:'cut'};clips.push(c);let probe=document.createElement('video');probe.preload='metadata';probe.src=url;probe.onloadedmetadata=()=>{c.duration=probe.duration||3;c.end=c.duration;render()}});sel=Math.max(0,clips.length-1);cursorTime=0;render()};
function transitionSheet(i){activeBoundary=i;let current=clips[i]?.transition||'cut',opts=[['cut','Coupe nette','Sans effet'],['dissolve','Fondu enchaîné','0,35 seconde'],['fade','Fondu noir','0,35 seconde'],['flash','Flash','Impact rapide'],['zoom','Zoom doux','Entrée dynamique']];sheet('<h2>Transition</h2><p class="cameraHint">Effet entre le plan '+(i+1)+' et le plan '+(i+2)+'.</p><div class="transitionGrid">'+opts.map(o=>'<button class="transitionOption '+(current===o[0]?'active':'')+'" data-transition="'+o[0]+'"><b>'+o[1]+'</b><small>'+o[2]+'</small></button>').join('')+'</div>')}
function animateTransition(index){if(index<1)return;let kind=clips[index-1]?.transition||'cut',v=$('#viewer'),frames={dissolve:[{opacity:.05},{opacity:1}],fade:[{opacity:0,filter:'brightness(0)'},{opacity:1,filter:'brightness(1)'}],flash:[{opacity:.25,filter:'brightness(2.5)'},{opacity:1,filter:'brightness(1)'}],zoom:[{opacity:.4,transform:'scale(1.08)'},{opacity:1,transform:'scale(1)'}]}[kind];if(frames&&v.animate)v.animate(frames,{duration:350,easing:'ease-out'})}
async function ensureReady(v){if(v.readyState>=1)return;await new Promise((ok,bad)=>{v.addEventListener('loadedmetadata',ok,{once:true});v.addEventListener('error',bad,{once:true});setTimeout(ok,1800)})}
async function playTimeline(){if(!clips.length)return note('Ajoute une vidéo pour lancer la lecture.');let token=++playToken,v=$('#viewer');if(cursorTime>=total()-.12){cursorTime=0;v.pause();try{v.currentTime=0}catch{}updateCursor()}let start=locate(cursorTime);setPlayIcon(true);for(let i=start.i;i<clips.length&&playing&&token===playToken;i++){let c=clips[i],local=i===start.i?start.local:0;sel=i;if(v.src!==c.url){v.src=c.url;v.load()}try{await ensureReady(v);v.pause();v.currentTime=Math.min(c.end-.001,c.start+local*c.speed);v.muted=!original;animateTransition(i);await v.play()}catch{setPlayIcon(false);return note('Safari a bloqué la lecture. Appuie à nouveau sur lecture.')}await new Promise(resolve=>{let frame=()=>{if(!playing||token!==playToken)return resolve();let progressed=Math.max(0,(v.currentTime-c.start)/c.speed);cursorTime=locateStart(i)+Math.min(dur(c),progressed);updateCursor();if(v.currentTime>=c.end-.04||v.ended){v.pause();return resolve()}requestAnimationFrame(frame)};frame()})}if(token===playToken){cursorTime=total();v.pause();setPlayIcon(false);updateCursor()}}
function stopTimeline(){playToken++;$('#viewer').pause();setPlayIcon(false)}
$('#play').onclick=()=>playing?stopTimeline():playTimeline();let ph=$('#playhead');ph.addEventListener('pointerdown',e=>{if(!clips.length)return;stopTimeline();draggingCursor=true;ph.setPointerCapture(e.pointerId);seekTo(timeForClientX(e.clientX))});ph.addEventListener('pointermove',e=>{if(draggingCursor)seekTo(timeForClientX(e.clientX))});ph.addEventListener('pointerup',e=>{draggingCursor=false;try{ph.releasePointerCapture(e.pointerId)}catch{}});$('#videoTrack').addEventListener('pointerdown',e=>{if(e.target.closest('.handle,.addClip,.transitionChip'))return;stopTimeline();seekTo(timeForClientX(e.clientX))});$('.ruler').addEventListener('pointerdown',e=>{if(!clips.length)return;stopTimeline();let r=e.currentTarget.getBoundingClientRect();seekTo(((e.clientX-r.left)/r.width)*total())});
$('#safeToggle').onclick=()=>{let p=$('.preview'),open=p.classList.toggle('editorFullscreen');document.body.classList.toggle('preview-open',open);$('#safeToggle').setAttribute('aria-label',open?'Fermer le plein écran':'Plein écran')};
function mediaSheet(){sheet('<h2>Ajouter un plan</h2><div class="mediaChoices"><button class="mediaChoice" data-media-source="camera">'+svg('<path d="M4 8h3l2-2h6l2 2h3v10H4z"/><circle cx="12" cy="13" r="3"/>')+'<b>Filmer maintenant</b></button><button class="mediaChoice" data-media-source="library">'+svg('<path d="M4 5h16v14H4zM4 15l4-4 4 4 2-2 6 6"/>')+'<b>Importer</b></button></div><p class="cameraHint">Conseil vlog : caméra arrière, vertical 9:16, 1080p à 30 i/s. Sur iPhone, la caméra native s’ouvre directement.</p>')}
let cam=document.createElement('input');cam.type='file';cam.accept='video/mp4,video/*';cam.capture='environment';cam.hidden=true;document.body.appendChild(cam);cam.onchange=()=>{if(cam.files?.length){importFiles(cam.files);close();cam.value=''}};$('#addMedia').onclick=mediaSheet;
const loadV36=load;load=function(){let v=$('#viewer'),c=cur();v.preload='auto';loadV36();if(!c||v.dataset.previewed===c.url)return;let showFirstFrame=()=>{if(playing||cur()!==c)return;v.pause();let first=Math.min(Math.max(c.start+.03,0),Math.max(c.start,c.end-.01));try{v.currentTime=first}catch{}v.dataset.previewed=c.url};if(v.readyState>=2)showFirstFrame();else v.addEventListener('loadeddata',showFirstFrame,{once:true})};
const oldActionV34=action;action=function(k){if(k==='transitions')return transitionSheet(Math.min(activeBoundary,Math.max(0,clips.length-2)));return oldActionV34(k)};
$('#sheet').addEventListener('click',e=>{let tr=e.target.closest('[data-transition]');if(tr){if(clips[activeBoundary])clips[activeBoundary].transition=tr.dataset.transition;render();close();return note('Transition appliquée.')}let src=e.target.closest('[data-media-source]');if(src){if(src.dataset.mediaSource==='camera')cam.click();else $('#files').click();return}let tpl=e.target.closest('[data-x="copy"]');if(tpl){caption=tpl.dataset.copy.replace(/\|/g,'\n');let input=$('#newCaption');if(input)input.value=caption;$('#caption').innerHTML=caption.replace(/\n/g,'<br>');$('#textLayer').style.display='flex';$$('.templateCard').forEach(x=>x.classList.toggle('active',x===tpl))}let col=e.target.closest('[data-x="color"]');if(col){txtColor=col.dataset.color;$('#caption').style.color=txtColor}let font=e.target.closest('[data-x="font"]');if(font){txtFont=font.dataset.font;$('#caption').style.fontFamily=txtFont}},true);
let f=$('#files');f.setAttribute('accept','video/mp4,video/*');f.addEventListener('change',()=>setTimeout(close,0));render();
});
